### ISSUE TITLE
Add README or Empty file 

### ISSUE THREAD

**Issue by aadityasaraiya** [ros-industrial/workcell_explorer#1]
Hey! 
This is the empty repository for my Google Summer of Code project on creation of a **ROS Package for Robotic WorkCell Discovery**. The abstract can be seen on this [link](https://summerofcode.withgoogle.com/projects/#6587806298669056). 

Currently, the repository is empty. Can someone please add a blank README or a License file so that I can fork the repository and push the code with which I have been working with for this project. 

Thanks!
Aaditya Saraiya

**Comment by gavanderhoorn** [comment]
I'm willing to do that, but it's not necessary: just add `https://github.com/ros-industrial/workcell_explorer.git` as a remote to your local git repo.

This is also explained on the main repository page.

**Comment by gavanderhoorn** [comment]
Do make sure to add both a readme and the license file btw.

**Comment by aadityasaraiya** [comment]
Thanks for the advice @gavanderhoorn Will the license be the MIT license for this case?

**Comment by gavanderhoorn** [comment]
I'm not aware of what you discussed with your project coordinators (@Levi-Armstrong and Alex). Most software in ROS-Industrial is Apache 2 though.

Why do you believe it should be MIT?

**Comment by aadityasaraiya** [comment]
I haven't discussed this yet with @Levi-Armstrong. I was going through a few packages on ROS Industrial and most of them do seem to have BSD 3 or Apache 2. No specific reason for mentioning MIT. Should I keep it as Apache 2.0 and edit it after consulting with @Levi-Armstrong once? 

I added `https://github.com/ros-industrial/workcell_explorer.git` as remote as follows `git remote add origin https://github.com/ros-industrial/workcell_explorer.git` and then followed with `git push -u origin master`. 

However, I am getting `remote: Permission to ros-industrial/workcell_explorer.git denied to aadityasaraiya.` as I don't have permissions to upload to this repo. 

Please do tell me if I am making some silly error.

**Comment by gavanderhoorn** [comment]
Let's keep at as Apache 2 for now. We can always change it later.

I've just invited you to the repository and given you write access.

**Comment by aadityasaraiya** [comment]
Sounds fair. Thanks again Gijs.

**Comment by gavanderhoorn** [comment]
It's somewhat off-topic, but I did not want to open a new issue for this.

If I may suggest:

 - avoid using sub modules, use a `.rosinstall` file instead to populate a workspace with the necessary packages
 - avoid versioning the `.catkin_tools` directory: it's per-user and *can* be versioned in some cases, however in this particular case I don't believe it contains anything interesting. How did that directory end up in your source space?

**Comment by aadityasaraiya** [comment]
+ Regarding the .catkin_tools directory, the issue was that by mistake while doing `git init ` I initialized the remote and added files from the workspace base directory instead of the src. Hence, I had to remove everything and start again. The `.catkin_tools` crept in from there as it was hidden file. I will remove it.

+ Thanks for the suggestion regarding `.rosinstall` file. I will test the creation and execution of that file once and update the repo with it.   

+ An additional thing, the `industrial_core` and `universal_robot` packages are populated locally, however, in the repo, they are coming as blank folders. So I am just trying to figure that out as well.

**Comment by gavanderhoorn** [comment]
@aadityasaraiya wrote:
> An additional thing, the `industrial_core` and `universal_robot` packages are populated locally, however, in the repo, they are coming as blank folders. So I am just trying to figure that out as well. 

that is just how submodules are represented by github.

But as I wrote earlier: don't use them. There's no need and they can be confusing.

**Comment by aadityasaraiya** [comment]
Thanks a lot. I found out that the blank folders are actually gitlinks to represent submodules. Using .rosinstall does make sense, so I will implement the same and avoid submodules.
